### ISSUE TITLE
  CustomStoryEditorController can not called .

### ISSUE THREAD

**Issue by jtaxiexpress** [TchatchoKemajou/custom_story_editor#1]
Hi , I want use this package .Because it encompasses all the features I was trying to create. You are fantastic.

## Issue
I could not called CustomStoryEditorController

<img width="600" alt="スクリーンショット 2024-08-08 18 56 26" src="https://github.com/user-attachments/assets/01088ec9-849a-431c-a58b-01465f3b0ff7">

### Flutter doctor 
```
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6 23G80 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```
---
Can you publish an example Flutter Project using this package?
I would like to refer to it.

**Comment by TchatchoKemajou** [comment]
use this import 

"import 'package:custom_story_editor/src/controller/controller.dart';"

I will resolve this issue in a future release and add sample code.

**Comment by TchatchoKemajou** [comment]
use this import

"import 'package:custom_story_editor/src/controller/controller.dart';"

I will resolve this issue in a future release and add sample code.

Le jeu. 8 août 2024 à 11:00, jtaxiexpress ***@***.***> a
écrit :

**Comment by jtaxiexpress** [comment]
Thanks for reply !
It is worked . 

import 'package:custom_story_editor/src/controller/controller.dart';
